export const getContenido = (idContrato: string): string => {
  if (idContrato == 'LPADS') {
    return '<p>1.- Servicio de Asesoría de Posicionamiento <strong>PAGADO en GOOGLE</strong> Adwords</p><p>&nbsp;</p><ul><li>Capacitación a distancia - Bajo el medio digital que se acuerde</li><li>Análisis de la web a posicionar</li><li>Recomendaciones </li><li>Configuración de la Cuenta</li><li>Capacitación de Uso de Google SEM </li><li>Manuales de Uso </li><li>Tiempo de Capacitación: Max 3 horas </li><li>Estrategias de pago </li><li>Capacitación en la publicidad pagada por el mismo cliente </li><li>Entrega de Manuales y Material</li><li><span style="color: windowtext;">TIEMPO: 01 día hábil&nbsp;</span></li></ul><p><br></p>'
  } else if (idContrato == 'LPMAPS') {
    return '<p><strong style="color: red;">1.- Ubicación de negocio o empresa en Google Maps</strong></p><ul><li>Configuramos tu dirección en Google Maps a través de tu perfil o cuenta de GMAIL </li><li>Verificación de la cuenta</li><li>Dirección exacta del negocio y empresa - <strong>01 sola SEDE</strong></li><li>Alta de Google Maps</li><li>Verificación de Google hasta <strong style="background-color: yellow;">05 días</strong></li></ul><p>&nbsp;</p><p>TIEMPO DE DESARROLLO: <span style="color: red;">01 día hábil</span> </p><p><br></p>'
  } else if (idContrato == 'LPSEO') {
    return '<p><strong style="color: red;">1.-Propiedad Verificada: </strong></p><ul><li>Verificación desde Gmail y añadir DNS</li><li>Verificar&nbsp;Google console search y listo la propiedad es del cliente</li><li>Realizar&nbsp;solicitud de indexación para que la URL pueda aparecer en Google</li><li>Propiedad Verificada</li><li>Inicio de SEO, trabajo con Palabras claves, Script y otras técnicas de Posicionamiento</li><li>El cliente nos remite :</li><li>Cuenta de GMAIL + Contraseña (es su propiedad)</li><li>ACCESOS A SU HOSTING ACTUAL</li></ul><p><br></p><p>TIEMPO DE DESARROLLO: <span style="color: red;">02&nbsp;días hábiles </span>&nbsp;</p>'
  } else if (idContrato == 'LPBRO') {
    return '<ul><li><strong>Información requerida (imágenes, datos de contacto, fotos propias)</strong></li><li><strong>Envió de logotipo editable. </strong></li><li><strong>(Se realizará un Análisis previo antes de la construcción del Brochure)</strong></li><li><strong>Hasta (01) Propuesta de Brochure de </strong><strong style="background-color: yellow;">6 caras </strong><strong>– 3 HOJAS </strong></li><li class="ql-align-justify">Análisis de la información enviada para la <strong>construcción del Brochure.</strong></li><li>Coordinación directa, con el cliente para el desarrollo del Brief o cuestionario.</li></ul><p><strong>Propuestas:</strong></p><ul><li>Recibirás (01 Desarrollo &amp; Diseños de <strong>Brochure Digital-impresión</strong>) Profesional. <span style="background-color: yellow;">6 </span><strong style="background-color: yellow;">caras </strong><strong>–&nbsp;3 HOJAS </strong></li><li><strong>100 % originales</strong></li><li><strong>1 diseñador dedicado</strong></li><li><strong>Modificaciones (</strong><strong style="color: red;">02 cambios en el diseño aprobado</strong>). <strong><u>No se otorgarán más cambios según el plan contratado.</u></strong></li></ul><p><strong>Entrega del Logotipo (02 días hábiles</strong>) según la respuesta inmediata del cliente</p><p>Entregables de <strong>Brochure Final</strong>:</p><p>Archivos Editables: <strong>Ilustrador o PSD // </strong>JPG imagen</p>'
  } else if (idContrato == 'LPREEL') {
    return '<p><strong style="background-color: yellow;">EDICION DE VIDEO </strong></p><p><br></p><ul><li>Desarrollo de Reel o Edición de Video de hasta 2 minutos. Saludo o presentación de su empresa o negocio</li><li>Cliente nos remite Logo en versión editable, Fotos o Videos Cortos, Imágenes &amp; Eventos cafer SAC solo Edita</li><li>Incluye Efectos y Musicalización&nbsp;&nbsp;</li><li>Desarrollo StoryBoard : Presentación al cliente&nbsp;</li><li>Locución en Off - INCLUYE (se remiten 2 propuestas)</li><li>Entregable vía DRIVE</li><li><strong style="color: rgb(51, 51, 51);">Tiempo de producción (total): </strong><strong style="color: red;">05 días hábiles </strong></li></ul><p><strong style="background-color: yellow;">Propuestas:</strong></p><ul><li>Recibirás un desarrollo y edición de su video</li><li>100 % originales</li><li>1 profesional dedicado</li><li>Resolución 1920x1080, alta calidad.</li><li>Modificaciones (<strong style="color: red;">02 cambios</strong>) por Video. <strong><u>No se otorgarán más cambios según el plan contratado.</u></strong></li></ul><p><br></p><p><strong style="background-color: yellow;">Entrega del Video en Drive (Descargar)</strong><strong> </strong></p>'
  } else if (idContrato == 'LPHOST') {
    return '<ul><li>Espacio de Disco de Duro&nbsp;de hasta 1 gb&nbsp;&nbsp;</li><li>Alojamiento <strong>(Solo 1 Dominio)&nbsp;coba.com.pe</strong></li><li>Redirección de E-mail&nbsp;(Ilimitado)</li><li>Setup <strong>(Gratis) </strong></li><li><strong>Sin CPanel de control </strong></li><li>Hasta 50 correos , cliente nos remite su listado</li><li>Entrega de <strong>Contrato (VIRTUAL) </strong></li><li><strong>Costos de migración de dominio son asumidos por el cliente </strong></li><li><strong>Backup de su pagina actual </strong></li><li><strong>Asesoría en compra de correos gsuite </strong></li></ul><p>&nbsp;</p><p><strong style="background-color: yellow;">CONDICION:</strong> PAGO 100% DEL PLAN ADQUIRIDO</p><p>&nbsp;</p><p><strong style="background-color: yellow;">Fecha DE INICIO -&nbsp;/07/2023</strong></p><p><strong style="background-color: yellow;">Fecha DE RENOVACIÓN&nbsp;-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/07/2024</strong></p>'
  } else if (
    idContrato == 'LP69' ||
    idContrato == 'LP69AM' ||
    idContrato == 'LP69AM2' ||
    idContrato == 'LPEXC' ||
    idContrato == 'LPEXCAM' ||
    idContrato == 'LPEXCAM2'
  ) {
    return '<p class="ql-align-justify"><strong>DISEÑO DE </strong><strong style="background-color: yellow;">01 LOGO</strong><strong style="color: red;">: </strong><strong>&nbsp;</strong></p><ul><li><strong>Brief o Cuestionario de la empresa.&nbsp;</strong><span style="background-color: yellow;">(Se realizará un Análisis previo antes de la construcción del Logotipo)</span></li><li>Hasta <strong style="background-color: yellow;">(01)</strong><strong> de Propuestas de diseño de LOGO </strong></li><li class="ql-align-justify">Análisis el Brief para la <strong>construcción del Logotipo.</strong></li><li class="ql-align-justify"><strong>Diseño o Rediseño de Logo </strong></li><li>Coordinación directa, con el cliente para el desarrollo del Brief o cuestionario.</li></ul><p><strong style="background-color: yellow;">Propuestas:</strong></p><ul><li>Recibirás (01 propuestas) Profesionales</li><li>100 % originales</li><li>1 diseñador dedicado</li><li>Modificaciones (<strong style="color: red;">03 cambios en el diseño aprobado</strong>). <strong><u>No se otorgarán más cambios según el plan contratado.</u></strong></li></ul><p>Entrega del Logotipo (<strong>02 días</strong> Hábiles. Teniendo en cuenta la respuesta inmediata del cliente.</p><p>Entregables del Logotipo Final: Archivos Editables y <strong>sustentación del LOGOTIPO APROBADO</strong>: <strong>Ilustrador o PSD – PNG – JPG –PDF </strong></p><p class="ql-align-center"><br></p><p class="ql-align-center"><strong style="background-color: yellow;">No incluye adaptación de personaje, ni&nbsp;vectorización.</strong></p><p><strong>&nbsp;</strong></p><ul><li><strong>01 Diseño de letrero. Según medidas del cliente – 1 propuesta </strong></li><li><strong>Hasta dos cambios&nbsp;</strong></li></ul>'
  } else if (idContrato == 'LPTV') {
    return '<p class="ql-align-justify"><strong>DESARROLLO &amp; DISEÑO de TIENDA VIRTUAL - ECOMMERCE - Plan GOLDEN</strong></p><p class="ql-align-justify"><strong>&nbsp;</strong></p><ul><li>Hasta 8 internas. A medida del cliente - Remite su ejemplo</li><li>Desarrollamos un Brief A MEDIDA</li><li>Integración de Carrito de COMPRAS.</li><li><strong>EL COSTO POR LA INTEGRACIÓN DEL SERVICIO DE COMERCIO ELECTRÓNICO, ES ASUMIDO POR EL CLIENTE</strong> </li><li>Trabajamos nuestra programación y Maquetación desde CERO </li><li>Programación en PHP - Framework </li><li>Base de Datos Myql </li><li>Soporte Ilimtados de productos </li><li>NO Utilizamos plantillas o CMS Gratuitos de Internet</li><li>WEB desarrollada desde CERO </li><li>Formularios de Contacto Dinámico. MAIL de repuesta al visitante.</li><li>Ubicación de la empresa o negocio a través de Google Maps.</li><li>Seguridad Anti Spam</li><li>Interacción con Redes Sociales.</li><li>Podrá ADMINISTRAR Hasta 4 Internas.</li><li>Entrega de acceso al administrador.</li><li>Manual de Usuario.</li><li>Capacitación del sistema (vía&nbsp;VIRTUAL).</li><li>Soporte Técnico. Por 06 mes (Solo atendemos incidencias o fallas en nuestro servicio + (01) cambio textuales e imágenes).</li><li>Técnica de Posicionamiento Web (SEO).</li></ul><p><strong>&nbsp;</strong></p><p><strong>ALTA DE GOOGLE - TIENDA VIRTUAL :</strong></p><p><br></p><ul><li>Propiedad Verificada</li><li>Inicio de SEO, trabajo con Palabras claves, Script y otras técnicas de Posicionamiento</li><li>Ubicación del negocio en Google MAP</li><li>Retoque Fotográfico de Hasta 10</li></ul><p><br></p><p><strong>EL CLIENTE NOS REMITE:</strong></p><p><br></p><ul><li>Logotipo editable (PSD – Ai – CDR).</li><li>Fotos e imágenes en buena resolución.</li><li>Entrega de datos de contacto</li><li class="ql-align-justify">Credenciales a su hosting actual&nbsp;</li></ul>'
  } else {
    return ''
  }
}
